name: Testing
on: push

jobs:
  network_project:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests
      run: |
        pip install --user django
        pip install Pillow
        python manage.py makemigrations
        python manage.py migrate
        python manage.py test
