name: Testing
on: push

jobs:
  network_project:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests
      run: |
        pip3 install --user django
        python manage.py test
